### ISSUE TITLE
StringView::find(char) + Emscripten + SIMD128 sometimes fails to find character

### ISSUE THREAD

**Issue by pezcode** [mosra/corrade#188] opened 2024-10-15 17:01 UTC
After a little bit of debugging the issue seems to be here:
https://github.com/mosra/corrade/blob/b6f0709a3be7c83eb1200aa2f6d88fcdb4fa10fc/src/Corrade/Containers/StringView.cpp#L687-L692
It's using `data` when it should be using `i`.

**Comment by mosra** [comment] 2024-10-15 17:08
Heh, that's rather _bad_... I was pretty sure the tests were covering this sufficiently enough.

**Comment by pezcode** [comment] 2024-10-15 17:34
> Do you know, off the top of your head, what min version should I use to get SIMD128 working? 1.39.6 is too old, it seems.

Not 100% certain, no. The only changelog entry that looks related is this for 1.39.17:
> Removed obsolete SIMD.js support (-s SIMD=1). Use -msimd128 to target Wasm SIMD.

**Comment by mosra** [comment] 2024-10-15 17:42
I'm an idiot, I have it documented: https://doc.magnum.graphics/corrade/Corrade_8h.html#a56ef81b7da04c3cb95250869aa6ae41c

But if I use 2.0.18, the CI will no longer test against 1.39. Oh, or I could split it like for Magnum, where the WebGL 1 builds are 1.39 and WebGL 2 are 2.0.25. Will do that, then.

**Comment by mosra** [comment] 2024-10-16 22:55
It took a day of suffering, but:

- A fix is in 2d51d71c625c895601574e287f29e82b79e23678, and the other NEON-specific issue you reported on Gitter is fixed in a1ae77458f034ee44587027687f4a2f3bc5740ca. Both were ultimately a regression since 5b4e2a7dff9b087211d1f647ed112e7d1f0bc230.
- Then, f012f2df850eba9dc271525e964c96bab63738c2...ced65a6baf3f09fdbccace8753e148efd2d7bcf7 hardens tests for string APIs in order to make sure the root cause for the NEON bug is caught, and adds a WASM SIMD128 build on the CI to ensure regressions in WASM SIMD code don't slip through again.

**Closed by mosra** 2024-10-16 22:55 UTC
Labels: changelog mention added

**Comment by pezcode** [comment] 2024-10-16 23:36
Thank you 😌 And sorry for the on-going Emscripten disasters, should hopefully be the last one for a while

**Comment by mosra** [comment] 2024-10-17 08:42
That's on me, I should have made sure that the WASM SIMD codepaths have a dedicated CI job in the first place.
